const WORK_TYPE_PROCREATE = 'Procreate';
const WORK_TYPE_FIRE_ALPACA = 'Fire Alpaca';
const WORK_TYPE_PAINT = 'Paint';
const WORK_FILTER_DIGITAL = 'Digital';
const WORK_FILTER_PAINT = 'Paint';
const WORK_FILTER_ALL = 'All';

const WORK_TYPES = [
    { text: 'Select One', value: null }, 
    WORK_TYPE_PROCREATE, 
    WORK_TYPE_FIRE_ALPACA, 
    WORK_TYPE_PAINT
];

const WORK_FILTERS = [
    WORK_FILTER_ALL,
    WORK_FILTER_DIGITAL,
    WORK_FILTER_PAINT
];

const TYPES_FILTERS_MAP = {};
TYPES_FILTERS_MAP[WORK_TYPE_PROCREATE] = WORK_FILTER_DIGITAL;
TYPES_FILTERS_MAP[WORK_TYPE_FIRE_ALPACA] = WORK_FILTER_DIGITAL;
TYPES_FILTERS_MAP[WORK_TYPE_PAINT] = WORK_FILTER_PAINT;

export { 
    WORK_FILTERS,
    WORK_TYPES,
    TYPES_FILTERS_MAP,
    WORK_FILTER_ALL 
};

